development:
  admin:
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - steve.vantuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlake@virginia.edu
    - hparekh@nd.edu
    - shanita@curationexperts.com
    - alicia@curationexperts.com
    - gamontoya@ucsd.edu
    - rkati@email.unc.edu
    - jrc88@cornell.edu
    - brian.mcbride@utah.edu
    - kmusio@artic.edu
    - jmfrenzel@example.com
    - cjcolvar@indiana.edu
production:
  admin:
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - steve.vantuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlake@virginia.edu
    - hparekh@nd.edu
    - shanita@curationexperts.com
    - alicia@curationexperts.com
    - gamontoya@ucsd.edu
    - rkati@email.unc.edu
    - jrc88@cornell.edu
    - brian.mcbride@utah.edu
    - kmusio@artic.edu
    - jmfrenzel@example.com
    - cjcolvar@indiana.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
